title: Gerson Morales
logo: /assets/img/Head Shot.png
description:
- Master of Analytics student @ UC Berkeley 
-  Connect with me on <a href="http://https://www.linkedin.com/in/gersonmoralesd/">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
