title: Gerson Morales Deras
logo: /assets/img/Head Shot.png
description: | 
Master of Analytics student @ UC Berkeley
Connect with me on [LinkedIn](https://www.linkedin.com/in/gersonmoralesd/)
show_downloads: false
theme: jekyll-theme-minimal
